name: Build main

on: [pull_request, release]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Install local tools
        run: dotnet tool restore
      - name: Build
        run: dotnet perla build

      - name: Upload App Build Artifact
      - uses: actions/upload-artifact@v2
        with:
          name: App
          path: /home/runner/work/dist/
